### ISSUE TITLE
AWS S3 Setup Script is broken/throwing errors

### ISSUE THREAD

**Issue by ashwin-patil** [Azure/Azure-Sentinel#12534]
**Describe the bug**
I am trying to run the Automated Setup section in Amazon Web Services S3 via provided script and it is thorwing an error message and also going into endless loop.

**To Reproduce**
1. Go to Microsoft Sentinel /USOP portal. 
2. Click on Data Connectors and then select Amazon Services S3 Connector. If it is not available , install AWS Solution from Content Hub
3. Scroll down to Automated Setup section and Download and extract the files from the following link: [AWS S3 Setup Script](https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/AWS-S3/ConfigAwsS3DataConnectorScripts.zip).
4. Go through initial configuration of AWS CLI and OIDC Provider creation, lastly provide sentinel workspace Id. 
5. See error
System.Management.Automation.RemoteException Error parsing parameter '--tags': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 3 (char 2) JSON received: [{Key:Operator,Value:Microsoft_Sentinel_Automation_Script}]

```
Executing: aws iam create-role --role-name OIDC_OIDC_MSSentinel --assume-role-policy-document {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Federated":"arn:aws:iam::0129345678901:oidc-provider/sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/"},"Condition":{"StringEquals":{"sts:RoleSessionName":"MicrosoftSentinel_<scrubbed workspaceId>","sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/:aud":"api://1462b192-27f7-4cb9-8523-0f4ecb54b47e"}},"Action":"sts:AssumeRoleWithWebIdentity"}]} --tags [{"Key":"Operator","Value":"Microsoft_Sentinel_Automation_Script"}] 2>&1
Retrying...
Again same error in until 3 attempts and failing with below error.
Action was unsuccessful after 3 attempts. Please review the errors and try again.
```

**Expected behavior**
Successful creation of roles with trust policies, in case of any JSON parsing error. Clear instructions of what to do next instead of rerunning the same 3 times with same error with no instructions to resolve.

**Screenshots**

<img width="1729" height="829" alt="Image" src="https://github.com/user-attachments/assets/4972a523-666a-4412-ac6c-c9a562a7584e" />

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Terminal - PowerShell

**Additional context**

**Comment by swiftsolves-msft** [comment]
[like]  Nathan Swift reacted to your message:
________________________________
From: Ashwin Patil ***@***.***>
Sent: Wednesday, July 16, 2025 12:21:26 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/Azure-Sentinel] AWS S3 Setup Script is broken/throwing errors (Issue #12534)

[https://avatars.githubusercontent.com/u/11397335?s=20&v=4]ashwin-patil created an issue (Azure/Azure-Sentinel#12534)<https://github.com/Azure/Azure-Sentinel/issues/12534>

Describe the bug
I am trying to run the Automated Setup section in Amazon Web Services S3 via provided script and it is thorwing an error message and also going into endless loop.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to Microsoft Sentinel /USOP portal.
  2.  Click on Data Connectors and then select Amazon Services S3 Connector. If it is not available , install AWS Solution from Content Hub
  3.  Scroll down to Automated Setup section and Download and extract the files from the following link: AWS S3 Setup Script<https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/AWS-S3/ConfigAwsS3DataConnectorScripts.zip>.
  4.  Go through initial configuration of AWS CLI and OIDC Provider creation, lastly provide sentinel workspace Id.
  5.  See error
System.Management.Automation.RemoteException Error parsing parameter '--tags': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 3 (char 2) JSON received: [{Key:Operator,Value:Microsoft_Sentinel_Automation_Script}]

Executing: aws iam create-role --role-name OIDC_OIDC_MSSentinel --assume-role-policy-document {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Federated":"arn:aws:iam::0129345678901:oidc-provider/sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/"},"Condition":{"StringEquals":{"sts:RoleSessionName":"MicrosoftSentinel_","sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/:aud":"api://1462b192-27f7-4cb9-8523-0f4ecb54b47e"}},"Action":"sts:AssumeRoleWithWebIdentity"}]} --tags [{"Key":"Operator","Value":"Microsoft_Sentinel_Automation_Script"}] 2>&1
Retrying...
Again same error in until 3 attempts and failing with below error.
Action was unsuccessful after 3 attempts. Please review the errors and try again.

Expected behavior
Successful creation of roles with trust policies, in case of any JSON parsing error. Clear instructions of what to do next instead of rerunning the same 3 times with same error with no instructions to resolve.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

  *   OS: Windows 11
  *   Terminal - PowerShell

Additional context
Add any other context about the problem here.

**Comment by v-tsawant** [comment]
Hi @ashwin-patil , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-tsawant** [comment]
Hi @ashwin-patil , The issue has been resolved and I have tested at my end. Could you please check from the below file by replacing at your end, Will raised the PR and attached to this GitHub issue. Thanks! 

[ConfigAwsS3DataConnectorScripts.zip](https://github.com/user-attachments/files/21259270/ConfigAwsS3DataConnectorScripts.zip)

**Comment by ashwin-patil** [comment]
> Hi [@ashwin-patil](https://github.com/ashwin-patil) , The issue has been resolved and I have tested at my end. Could you please check from the below file by replacing at your end, Will raised the PR and attached to this GitHub issue. Thanks!
> 
> [ConfigAwsS3DataConnectorScripts.zip](https://github.com/user-attachments/files/21259270/ConfigAwsS3DataConnectorScripts.zip)

Hey @v-tsawant It seems the fix is still not working.. Also notice the issue seems to be associated --tags parameter.

I think you need to debug `Get-SentinelTagInJsonFormat` and how it is being passed to tags parameter in multiple places in `AwsResourceCreator.ps1`  as it is used in multiple places. 

Here are the logs with error.

`Executing: aws iam create-role --role-name OIDC_NEW_CCSP_Sentinel --assume-role-policy-document {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Federated":"arn:aws:iam::0123456789012:oidc-provider/sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/"},"Condition":{"StringEquals":{"sts:RoleSessionName":"MicrosoftSentinel_<workspaceId>","sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/:aud":"api://1462b192-27f7-4cb9-8523-0f4ecb54b47e"}},"Action":"sts:AssumeRoleWithWebIdentity"}]} --tags {"Key":"Operator","Value":"Microsoft_Sentinel_Automation_Script"} 2>&1

System.Management.Automation.RemoteException Error parsing parameter '--tags': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 3 (char 2) 

JSON received: [{Key:Operator,Value:Microsoft_Sentinel_Automation_Script}]`

**Comment by v-tsawant** [comment]
HI @ashwin-patil , could you please confirm which PowerShell version you were using? required version is 7.5

**Comment by ashwin-patil** [comment]
> HI [@ashwin-patil](https://github.com/ashwin-patil) , could you please confirm which PowerShell version you were using? required version is 7.5

Hey @v-tsawant upgraded to PS 7.5 but still the same issue and error. I can see tags value is enclosed in quotes and in array but still throwing the same error

```
Executing: aws iam create-role --role-name OIDC_CCSP_NEW_Sentinel 
--assume-role-policy-document 
{"Version":"2012-10-17","Statement":[{"Effect":"Allow",
"Principal":{"Federated":"arn:aws:iam::0123456789012:oidc-provider/sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/"},"
Condition":{"StringEquals":{"sts:RoleSessionName":"MicrosoftSentinel_<workspaceId>",
"sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/:aud":
"api://1462b192-27f7-4cb9-8523-0f4ecb54b47e"}},
"Action":"sts:AssumeRoleWithWebIdentity"}]} 
--tags '[{"Key":"Operator","Value":"Microsoft_Sentinel_Automation_Script"}]' 2>&1

System.Management.Automation.RemoteException Error parsing parameter '--tags': Invalid JSON: 
Expecting property name enclosed in double quotes: line 1 column 3 (char 2) JSON received
[{Key:Operator,Value:Microsoft_Sentinel_Automation_Script}]

JSON received: [{Key:Operator,Value:Microsoft_Sentinel_Automation_Script}]
```

**Comment by TCS-chaitravimore** [comment]
Hi, I am facing the same issue. Is there a solution provided for this anywhere?
