### ISSUE TITLE
Preview image name casing issue

### ISSUE THREAD

**Issue by ericlanteigne-semperis** [Azure/Azure-Sentinel#2389]
**Describe the bug**
The Workbooks Metadata Validation failed with error message "Can't locate preview image file UnifiSGWhite.png under the Workbooks/Images/Preview directory" due to a file name mismatch. It is looking for "UnifiSGWhite.png" but the file is named " UniFiSGWhite.png". 
 

**To Reproduce**
1. Go to 'https://dev.azure.com/azure/Azure-Sentinel/_build/results?buildId=24025&view=logs&j=63ee3bc0-5b80-52de-bb29-481c2427e26c&t=dfd360ed-9887-56e7-cb8c-397962a0719d'

**Expected behavior**
Tests should not fail with content from master branch

**Screenshots**
![image](https://user-images.githubusercontent.com/84532420/120522820-4afb4980-c3a3-11eb-8a73-60d6f020b6fb.png)

![image](https://user-images.githubusercontent.com/84532420/120520936-63b72f80-c3a2-11eb-8b46-f34ff7168305.png)

**Additional context**
Made an update to my pull request after merging the latest changes from master branch and it seems the workbooks validation test is complaining about a file not found. Looks like there is a file that has one letter upper cased where as the workbook has it with lower case.

**Comment by shainw** [comment]
@ericlanteigne-semperis - I believe this is fixed in #1096

**Comment by ericlanteigne-semperis** [comment]
I double checked to see if maybe I did something wrong when merging master into my branch but I can still see the mismatch in names in master branch
![image](https://user-images.githubusercontent.com/84532420/121044355-7e631d00-c783-11eb-827d-84c3007fd2ec.png)

**Comment by ericlanteigne-semperis** [comment]
It seems the issue has been taken care of
