### ISSUE TITLE
Fortinet-GetEntityDetails not authenticating against Fortigate

### ISSUE THREAD

**Issue by scottbrien01** [Azure/Azure-Sentinel#2874]
**Describe the bug**
Receive error "Unexpected character encountered while parsing value: <. Path '', line 0, position 0."  when running function app Fortinet-GetEntityDetails

**To Reproduce**
1. Assign Fortinet-FortiGate-ResponseOnIP playbook to analytics rule
2. Trigger rule so that logic app fires
3. Logic app will get to "check address object is already in firewall" and will hang.
4. Check function app monitor to confirm that API is calling Fortinet-GetEntityDetails and that error is generated

**Expected behavior**
API should run through so that logic app can complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/86039729/130007691-16f35292-816e-4620-a71c-9ffa37377d60.png)

**Comment by scottbrien01** [comment]
Issue is due to the access_code not being appended to the request to the fortigate and reply has the following when unauthorised.

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

**Comment by scottbrien01** [comment]
Hi,
Wanted to check in to see if there were any thoughts on this one?

**Comment by v-rucdu** [comment]
@lior-tamir : This looks to be related to Playbooks, can you please take a look.. Thanks !!!

**Comment by scottbrien01** [comment]
Hi,
Wanted to check in to see if there was anything we could look at on this one?

**Comment by ashishsyal** [comment]
We are working on this one and will update once we have solution.

**Comment by anki-narravula** [comment]
Hi @scottbrien01  this bug is addressed now. Shall we close this issue ?

**Comment by v-rucdu** [comment]
We will close this issue, please reopen incase you still face any issues... Thanks!!!
