### ISSUE TITLE
Broken URL - Barracuda Cloud Gen Firewall Connector Configuration

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [Azure/Azure-Sentinel#5200]
The below URL mentioned in the steps to configure the Barracuda Cloud Gen Firewall connector does not work. 

https://aka.ms/sentinel-barracudacloudfirewall-function

This data connector depends on a parser based on a Kusto Function to work as expected. [Follow these steps](https://aka.ms/sentinel-barracudacloudfirewall-function) to create the Kusto functions alias, CGFWFirewallActivity.

**Comment by v-sabiraj** [comment]
Hey @HarrisburgUSysAdmin, the issue has been resolved follow these steps hyperlink should be working now, can you please verify, thanks.
![image](https://user-images.githubusercontent.com/94349919/174768785-79e976d2-e9eb-4ef1-9d33-27ee29533ec5.png)

**Comment by HarrisburgUSysAdmin** [comment]
We still get the below page not found.

![image](https://user-images.githubusercontent.com/52167303/174823064-4cfd2924-08d3-49d4-9c7f-eac45072b260.png)

**Comment by v-sabiraj** [comment]
Hey @HarrisburgUSysAdmin, the commit has be deployed in all regions, can you check it once now, thanks.

**Comment by v-sabiraj** [comment]
Hey @HarrisburgUSysAdmin, can you please check and verify if issue is fixed so it can be closed, thanks.

**Comment by HarrisburgUSysAdmin** [comment]
Yes, thank you for your help in resolving this.

**Comment by v-sabiraj** [comment]
Hey @HarrisburgUSysAdmin, closing this, thanks.
