### ISSUE TITLE
LastPass data connector no longer polling after upgrade

### ISSUE THREAD

**Issue by ianssoftcom** [Azure/Azure-Sentinel#6244]
**Describe the bug**
The LastPass solution was upgraded by disconnecting and removing the current Sentinel data connector for LastPass, and upgraded by installing the solution from the Sentinel content hub and reconnecting the data connector (CID and Provisioning Hash).

When looking at the LastPass event reporting logs, I see only 1 connection to the LastPass enterpriseAPI, where I used to see a regular connection every 10 minutes.

```
{
  "Time": "2022-09-28 03:45:27",
  "Username": "",
  "IP_Address": "52.154.254.182",
  "Action": "Reporting",
  "Data": "Initiated by API: Microsoft Sentinel CCP"
}
```

The Sentinel data connector has a "connected" status, but has not received new logs since the previous version was removed (3 weeks ago)

status: connected
provider: The Collective Consulting BV
Last log received: --

**To Reproduce**
Install the Lastpass Enterprise Activity Monitoring solution from the Sentinel content hub

**Expected behavior**
The LastPass solution for Sentinel should retrieve data from https://lastpass.com/enterpriseapi.php as before (March - September)

**Screenshots**

**Additional context**
I wanted to incorporate the addition of the API user, from #4484 and #4754 (thanks @ThijsLecomte)

I believe the previous version deployed in March that was working was 1.0.3 and the current version is 2.0.2

**Comment by Loule-Corro** [comment]
any update on this issue? we are facing it with 2.0.2, even with 1.0.3 after disconnect and reconnect.

**Comment by ThijsLecomte** [comment]
There seems to be an issue with the CCP, I am checking with Microsoft myself to see where this goes wrong.

**Comment by NikTripathi** [comment]
Hi @ianssoftcom Can you please test the below custom template and let us know the output.

Please deploy the custom template available on the below URL. It will update your solution and then please test the connector.

URL:- https://raw.githubusercontent.com/Azure/Azure-Sentinel/f3ad344e225e348e2d946f1dcf4ec696ebb3e8c7/Solutions/LastPass/Package/mainTemplate.json

Steps:- 
1: Go to Portal and search for deploy a custom template.
![image](https://user-images.githubusercontent.com/87809732/209349690-39e3d802-2e0c-4a8d-b5ba-667ff5d20ba3.png)
2: Click on build your own template in editor.
![image](https://user-images.githubusercontent.com/87809732/209349902-12d559d7-7667-4b5f-b4dd-6cca2fc576a7.png)
3: Remove the content and paste the content which is available on the above URL and click on save.
![image](https://user-images.githubusercontent.com/87809732/209350012-ce5cc030-98a4-4a03-a2c9-4875beecd5a5.png)
4: Select Resource group and workspace and then click on review + Create.
![image](https://user-images.githubusercontent.com/87809732/209350112-0c843a29-fd04-4768-975e-27feb0a489bb.png)
5: Once deployment is done please test the data connector and let us know the output. 

Thanks.

**Comment by ThijsLecomte** [comment]
Hi @NikTripathi 

Doesn't seem to be fixed, unfortunately. Getting another error right now:
![image](https://user-images.githubusercontent.com/42153270/209382783-fbe782d8-1b96-4207-805c-a03d743f2b53.png)
I copied/pasted the credentials from my postman, which is working correctly. Also tried reconnecting to ensure there was no issue.

Is there any way I can check raw logs to verify the output the API provides?

**Comment by ashishsyal** [comment]
Can you confirm if this is resolved

**Comment by ianssoftcom** [comment]
I am using an external polling process, so I can't test the CCP method. Although the note from @ThijsLecomte indicates that it is fixed.

**Comment by Loule-Corro** [comment]
I think his comment was that the problem is still happening, he just found another way to get data.

**Comment by ThijsLecomte** [comment]
@Loule-Corro I confirmed this is fixed and all is running well

**Comment by Loule-Corro** [comment]
OK good to know, I will give it a try. Thanks.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
