### ISSUE TITLE
PR validation builds fail for false positive on "Azure Sentinel" content search

### ISSUE THREAD

**Issue by keyoke** [Azure/Azure-Sentinel#7090]
**Describe the bug**
PR Validation builds are failing due to false positive, see screenshots below.

**Expected behavior**
Should not fail as the logic app conector only allows two values for this parameter.

**Screenshots**
Failing build

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/183547/212079555-1958195a-4478-4593-b5c5-25c97f11b6dc.png">

playbook 

<img width="971" alt="image" src="https://user-images.githubusercontent.com/183547/212079953-f967f8fa-5a4f-47d1-ac5e-abf5456583c2.png">

azure docs for targetProduct

<img width="874" alt="image" src="https://user-images.githubusercontent.com/183547/212079702-8f55c40a-949f-4fb7-8445-405beecfba0d.png">

**Comment by v-amolpatil** [comment]
@keyoke This issue is now fixed in master. Please update your branch with latest master.

**Comment by keyoke** [comment]
> @keyoke This issue is now fixed in master. Please update your branch with latest master.

hi @v-sabiraj - I have done so and pushed changes to my branch but seems the PR validation still fails for me

**Comment by keyoke** [comment]
> > @keyoke This issue is now fixed in master. Please update your branch with latest master.
> 
> hi @v-amolpatil - I have done so and pushed changes to my branch but seems the PR validation still fails for me

**Comment by v-amolpatil** [comment]
@keyoke We have fixed the issue in master so could you please take the latest master and let us know if it works.

**Comment by keyoke** [comment]
> @keyoke We have fixed the issue in master so could you please take the latest master and let us know if it works.

@v-amolpatil thanks yes this seems to pass for content validation now

**Comment by v-amolpatil** [comment]
Closing this as this is now resolved.
