### ISSUE TITLE
Exception thrown while ingesting Atlassian JIRA Audit logs using the connector

### ISSUE THREAD

**Issue by shashank-raina-nhs** [Azure/Azure-Sentinel#8088]
I am trying to connect the Atlassian Confluence and JIRA Data Connectors with Sentinel. While the confluence connector works perfectly fine, there are no logs from JIRA. I have found the following error from the exceptions table for the JIRA function app which is deployed with the data connector:

Result: Failure
Exception: TypeError: '>' not supported between instances of 'NoneType' and 'int'
Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 406, in _handle__invocation_request
call_result = await self._loop.run_in_executor(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 648, in _run_sync_func
return ExtensionManager.get_sync_invocation_wrapper(context,
File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper
result = function(**args)
File "/home/site/wwwroot/JiraAuditAPISentinelConnector/__init__.py", line 129, in main
get_result(generate_date())
File "/home/site/wwwroot/JiraAuditAPISentinelConnector/__init__.py", line 85, in get_result
if element_count > 0:

**Comment by shashank-raina-nhs** [comment]
Resolved

**Comment by MKaleem92** [comment]
Hey Shashank-raina-nhs, can you detail how you fixed this issue? I have ran through the set up multiple times but still getting the same error. Any help would be much appreciated.
